# Generated by Django 4.0.2 on 2022-03-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_description_listing_enddate_listing_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='enddate',
        ),
    ]
