# Generated by Django 4.0.2 on 2022-03-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bids_value_alter_listing_initialvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('listen', models.BooleanField()),
            ],
        ),
    ]
