# Generated by Django 4.0.2 on 2022-03-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listen',
            new_name='active',
        ),
    ]
