# Generated by Django 4.0.2 on 2022-03-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='userid',
            new_name='watcherid',
        ),
    ]
