# Generated by Django 4.0.2 on 2022-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_userid_watchlist_watcherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[(1, 'Toys'), (2, 'Animals'), (3, 'Furniture'), (4, 'Food'), (5, 'Other')], default='Toys', max_length=1),
        ),
    ]
