# Generated by Django 4.0.2 on 2022-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Toys', 'Toys'), ('Animals', 'Animals'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Other', 'Other')], default='Toys', max_length=9),
        ),
    ]
